# Generated by Django 3.0.1 on 2019-12-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyVal',
            fields=[
                ('key', models.CharField(max_length=511, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Key Value',
                'verbose_name_plural': 'KeyValues',
                'db_table': 'key_values',
            },
        ),
    ]
