# Generated by Django 3.0.1 on 2019-12-30 16:22

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(db_index=True, unique=True)),
                ('value', models.TextField()),
                ('ttl', models.DateTimeField(default=store.models.get_ttl_for_new_object)),
            ],
            options={
                'verbose_name': 'Key Value',
                'verbose_name_plural': 'KeyValues',
                'db_table': 'key_values',
            },
        ),
    ]
