# Generated by Django 3.0.1 on 2019-12-26 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyval',
            old_name='updated_at',
            new_name='last_update_or_view',
        ),
        migrations.RemoveField(
            model_name='keyval',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='keyval',
            name='viewed_at',
        ),
    ]
