# Generated by Django 3.0.1 on 2019-12-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20191226_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyval',
            name='last_update_or_view',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
