# Generated by Django 3.0.1 on 2019-12-26 15:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20191226_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyval',
            name='last_update_or_view',
        ),
        migrations.AddField(
            model_name='keyval',
            name='ttl',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 26, 15, 7, 52, 449917, tzinfo=utc)),
        ),
    ]
