# Generated by Django 3.0.1 on 2019-12-28 11:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20191226_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyval',
            name='ttl',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 28, 11, 9, 37, 879808, tzinfo=utc)),
        ),
    ]
